# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-03-11 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='用户名')),
                ('message', models.CharField(max_length=500, verbose_name='留言信息')),
            ],
            options={
                'verbose_name': '用户留言信息',
            },
        ),
    ]
